parameters:
  service-dir:
    default: "sdk/devcenter"
emit: [
  # "@azure-tools/typespec-apiview",
  "@azure-tools/typespec-autorest",
  "@azure-tools/typespec-csharp",
  "@azure-tools/typespec-java",
  "@azure-tools/typespec-python",
  "@azure-tools/typespec-ts",
]
linter:
  extends:
    - "@azure-tools/typespec-azure-core/all"
options:
  "@azure-tools/typespec-csharp":
    namespace : "Azure.Developer.DevCenter"
    clear-output-folder : true
    # new-project : false
    # model-namespace : false
  "@azure-tools/typespec-python":
    package-dir: "azure-developer-devcenter"
    package-name: "{package-dir}"
    package-mode: "azure-dataplane"
    models-mode: none
  "@azure-tools/typespec-ts":
    title: "Azure Developer DevCenter"
    generateMetadata: true
    package-dir: "developer-devcenter-rest"
    generateTest: true
    "emitter-output-dir": "{output-dir}"
    packageDetails:
      name: "@azure-rest/developer-devcenter"
      description: "Azure Developer DevCenter Client"
      version: "1.0.0-beta.3"
  "@azure-tools/typespec-java":
    package-dir: "azure-developer-devcenter"
    namespace: com.azure.developer.devcenter
